### PR TITLE
Make a Godot 4 supported version of the library

### PR DESCRIPTION
**Pull request by OmarShehata**
Resolves https://github.com/Federico-Ciuffardi/GodotTouchInputManager/issues/22.

This is branched off of @dave2's fork and includes additional fixes to make the library work with Godot 4. I've tested this version with the "Demo" project as well as the "GestureControlledCamera2D"

* https://github.com/Federico-Ciuffardi/GodotTouchInputManager-Demo/pull/4
* https://github.com/Federico-Ciuffardi/GestureControlledCamera2D/pull/7

**One remaining issue is that by default, users will get the following compiler error in Godot 4**:

```
W 0:00:06:0315   The method "as_text" overrides a method from native class "InputEvent". This won't be called by the engine and may not work as expected.
  <GDScript Error>NATIVE_METHOD_OVERRIDE
  <GDScript Source>InputEventScreenTwist.gd:18
```

This is because in Godot 4 the maintainers have decided to treat the case where you are overriding a native method through GDScript as an error due to it being ambiguous: https://github.com/godotengine/godot/issues/55024. In order to compile it, you'll need to go into Project Settings, toggle "Advanced Settings", find Debug > GDScript, and set "Native Method Override" to warn instead of error. The full path to this option is:

```
debug/gdscript/warnings/native_method_override
```

The other big problem is that the Godot 4 version of this library is not compatible with Godot 3. Easiest thing for now would be to keep it on a branch and have a big bold statement in the README directing people to this branch. Or alternatively just have them in separate folders?

### CODE REVIEW

**Comment by Federico-Ciuffardi** [comment]
This is great, thank you!

Some comments/questions:
* Why was the variable `raw_gesture` renamed to `raw_gesture_data`?
* There is a conflict preventing the merge, can you fix it?
* Perhaps it is better to change `as_text` to something like `to_text` or `as_string` to avoid the name conflict (and the need to change the project settings).
* About the compatibility issue, I agree, we can keep this in the `godot4support` branch and once this is merged I'll update the `master` branch README.
* I found a bug, If I press the screen with three or more fingers when I release them, the `index` of the touch events are all `-1`:
```
InputEventScreenTouch: index=0, pressed=true, position=((1183, 446)), double_tap=false
InputEventScreenTouch: index=1, pressed=true, position=((1419, 467)), double_tap=false
InputEventScreenTouch: index=2, pressed=true, position=((938, 435)), double_tap=false
InputEventScreenTouch: index=-1, pressed=false, position=((1183, 446)), double_tap=false
InputEventScreenTouch: index=-1, pressed=false, position=((1419, 467)), double_tap=false
InputEventScreenTouch: index=-1, pressed=false, position=((938, 435)), double_tap=false
```
This causes touches, taps and swipes to stop working. This doesn't happen in Godot 3, I'll be creating an issue on the Godot github soon.

**Comment by OmarShehata** [comment]
> Why was the variable raw_gesture renamed to raw_gesture_data?

This is because signals can now be used directly, like:

```
signal raw_gesture

raw_gesture.emit()
```

which means it will conflict with a variable of the same name. In my initial version I kept the `raw_gesture` variables the same and instead renamed the signals to all be `raw_gesture` -> `raw_gesture_signal`. But I switched to Dave's way instead. Lemme know if you have a preference here!

> Perhaps it is better to change as_text to something like to_text or as_string to avoid the name conflict (and the need to change the project settings).

I think that makes sense to me too since it's something everyone will encounter. The only drawback is you'll need to print native events with `as_text` and the custom ones as `as_string` but I think that's OK, the user can check the type of event before calling the function.

Other feedback makes sense to me, will update the PR soon!

**Comment by OmarShehata** [comment]
@Federico-Ciuffardi this should be ready for another look now

> There is a conflict preventing the merge, can you fix it?

I'm actually not seeing any conflict, neither on GitHub or locally when I fetched the latest `Federico-Ciuffardi:godot4support`. The godot4support here looks like it's same as master.

**Comment by Federico-Ciuffardi** [comment]
> I'm actually not seeing any conflict, neither on GitHub or locally when I fetched the latest Federico-Ciuffardi:godot4support. The godot4support here looks like it's same as master.

Oh, I see, merging doesn't cause conflicts, but rebasing does. If you prefer we can merge to avoid resolving conflicts.

**Comment by OmarShehata** [comment]
> Oh, I see, merging doesn't cause conflicts, but rebasing does. If you prefer we can merge to avoid resolving conflicts.

that would be great!

**Comment by Federico-Ciuffardi** [comment]
@OmarShehata I just merged all your PRs, thanks!

**Pull request merged**
